export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS = "FETCH_POSTS";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST = "FETCH_POST";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";

export const SET_LOADER = "SET_LOADER";
